### ISSUE TITLE
Activity Feed Item : Mentioned

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#143]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

As a CliqRex user, in my activity feed, I want to be notified a friend mentions me in a comment

### Acceptance Criteria

- when a friend mentions me in a comment on any media I want to be notified of that in my activity feed
- notification card should display the photo and name of user who mentioned me (Bob Ross)
- thumbnail of associated media should be displayed on right
- clicking on the user's photo (Bob Ross) should take me to that user's detail page
- clicking the text notification takes you to the media detail screen.
- clicking on the media thumbnail should load the media detail screen
- notification card should display how long ago action took place

### Exceptions

none

### Screenshots

![status_mention](https://user-images.githubusercontent.com/15748883/175035629-b8cc5f2c-a18d-49bf-90dd-268e892e4caf.png)

**Comment by palepinkdot** [comment]
Amending the acceptance criteria:
- clicking on the text notification should take me to the associated media detail screen and load the comments as an overlay
New:
- clicking the text notification takes you to the media detail screen.

"loading the comments as an overlay would be broken out to a separate issue. I'm not doing it myself because it is not a part of the activity feed which is what this story #140 is relevant to.
